name: Fetch CDN URLs Every 5 min

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-cdn-urls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch multiple channel data
        run: |
          # Read channel IDs from secrets (comma-separated)
          IFS=',' read -ra CHANNEL_IDS <<< "${{ secrets.CHANNEL_IDS }}"
          
          # Create a temporary file for individual responses
          rm -f temp_responses.txt
          
          # Fetch all channel data
          for channel_id in "${CHANNEL_IDS[@]}"; do
            channel_id=$(echo "$channel_id" | xargs)
            echo "Fetching data for channel ID: $channel_id"
            
            response=$(curl -s -H "Referer: https://dora-bash-live.blogspot.com/" \
              "https://proxy.animebash.workers.dev/?u=https://bashserver.xyz/fucku.php?id=${channel_id}")
            
            # Check if response is valid JSON
            if echo "$response" | jq empty 2>/dev/null; then
              echo "$response" >> temp_responses.txt
            else
              echo "Warning: Invalid response for channel $channel_id"
            fi
          done
          
          # Create single get.txt file with all channels
          if [ -f temp_responses.txt ]; then
            jq -s '.' temp_responses.txt > get.txt
            rm -f temp_responses.txt
          else
            echo "[]" > get.txt
          fi
          
          echo "Generated get.txt:"
          cat get.txt

      - name: Commit and push files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add get.txt
          git commit -m "Update channel data - $(date -u)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
